// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Amazon",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Amazon", targets: ["AATKit-Amazon"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Amazon",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATAmazonAdapter",
                    "AATDTBiOSSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Amazon"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATAmazonAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATAmazonAdapter.zip",
            checksum: "52e61df5df5fa5a7a0dc07e1ef907fa9da314f30062ec25ba5cb81c64fdd0bbf"
        ),
        .binaryTarget(
            name: "AATDTBiOSSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/DTBiOSSDK.zip",
            checksum: "ceb867f2b90172c0a6148b68f47b7bfcac9558b3bbde7820f32d32ed0f35f585"
        ),
    ]
)
